# Generated by Django 3.1.7 on 2021-03-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleversion',
            options={'get_latest_by': 'number'},
        ),
    ]
